#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[0].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[0].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[10].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[10].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[11].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[11].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[12].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[12].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[13].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[13].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[14].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[14].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[15].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[15].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[16].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[16].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[17].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[17].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[18].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[18].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[19].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[19].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[1].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[1].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[20].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[20].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[21].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[21].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[22].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[22].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[23].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[23].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[24].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[24].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[25].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[25].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[26].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[26].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[27].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[27].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[28].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[28].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[29].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[29].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[2].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[2].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[30].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[30].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[31].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[31].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[3].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[3].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[4].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[4].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[5].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[5].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[6].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[6].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[7].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[7].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[8].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[8].DFF/G_RisingEdgeClock.cdc_reg2]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[9].DFF/G_RisingEdgeClock.cdc_reg1]
#set_property ASYNC_REG true [get_cells base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[9].DFF/G_RisingEdgeClock.cdc_reg2]
#set_false_path -from [get_clocks [list clk_fpga_0 clkFbOut CLK100MHzraw CLK125MHzraw]] -to [get_cells [list base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/SyncBitCNT_CLR/G_RisingEdgeClock.cdc_reg1 #          base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/SyncBitCNT_CLR/G_RisingEdgeClock.cdc_reg2 #          base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_ClockMgmt_inst/SyncBit_reset125MHz/G_RisingEdgeClock.cdc_reg1 #          base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_ClockMgmt_inst/SyncBit_reset125MHz/G_RisingEdgeClock.cdc_reg2 #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[0].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[0].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[10].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[10].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[11].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[11].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[12].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[12].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[13].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[13].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[14].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[14].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[15].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[15].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[16].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[16].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[17].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[17].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[18].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[18].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[19].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[19].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[1].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[1].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[20].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[20].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[21].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[21].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[22].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[22].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[23].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[23].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[24].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[24].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[25].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[25].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[26].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[26].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[27].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[27].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[28].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[28].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[29].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[29].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[2].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[2].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[30].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[30].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[31].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[31].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[3].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[3].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[4].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[4].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[5].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[5].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[6].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[6].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[7].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[7].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[8].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[8].DFF/G_RisingEdgeClock.cdc_reg2} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[9].DFF/G_RisingEdgeClock.cdc_reg1} #          {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RDAD_WL_SS/SyncBuffer_NBRWINDOWS/SyncBuffer_GEN[9].DFF/G_RisingEdgeClock.cdc_reg2} #          base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/SyncBitNrst/G_RisingEdgeClock.cdc_reg1 #          base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/SyncBitNrst/G_RisingEdgeClock.cdc_reg2]]
# ----------------------------------------------------------------------------
# TIMING Constraint File
# ----------------------------------------------------------------------------


set_property async_reg true [get_cells -hierarchical *cdc_reg*]
set_false_path -from [get_clocks *] -to [get_cells -hierarchical *cdc_reg*]

set_property async_reg true [get_cells -hierarchical *DFF_AB*]
#set_false_path -from [get_clocks *] -to [get_cells -hierarchical *DFF_AB*]

set_property async_reg true [get_cells -hierarchical *DFF_B*]
set_false_path -from [get_clocks *] -to [get_pins -hierarchical -filter Name=~*DFF_AB/Q_reg/D]

#set_property DRIVE 16 [get_ports BB3]
#set_property SLEW FAST [get_ports BB3]
set_property DIFF_TERM TRUE [get_ports MONTIMING_N]
set_property DIFF_TERM TRUE [get_ports MONTIMING_P]







create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_ClockMgmt_inst/CLK125MHz_bufg]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_CS_S[0]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_CS_S[1]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_CS_S[2]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_CS_S[3]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_CS_S[4]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_CS_S[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 9 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[0]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[1]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[2]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[3]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[4]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[5]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[6]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[7]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/inst_DummyTriger/cnt_i[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_RS_S[0]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WR_RS_S[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe3]
set_property port_width 9 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[0]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[1]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[2]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[3]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[4]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[5]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[6]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[7]} {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WdoNumber[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list base_zynq_i/axi_dma_0_s2mm_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/CtrlBus_IxSL[CPUMode]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/dummytrigger_s]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/circBuffer/windowStorage]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list base_zynq_i/TARGET_C_TopLevel_Sy_0/U0/TC_RoundBuffer/WDOSTORE/WriteEn]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLK125MHz_bufg]
